### ISSUE TITLE
uniroot error

### ISSUE THREAD

**Issue by sdmiller93** [matteocereda/GSECA#1]
I am getting this error: 

```
Error in if (mu > x) uniroot(function(t) mnhyper(t) - x, c(0, 1))$root else if (mu <  : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In dhyper(support, m, n, k, log = TRUE) : NaNs produced
2: In d <= d[x - lo + 1] * relErr :
  longer object length is not a multiple of shorter object length
```
That I can't seem to resolve or find the issue. Any ideas on where to start with this? I am using my own dataset but it matches exactly the formats you show on your README

**Comment by matteocereda** [comment]
If you get this error only using your dataset, the issue may be connected with it. Can you please share the R traceback output and, at least the str() of your dataset? This would help

**Comment by sdmiller93** [comment]
This is the entire printout:

`
[*] loading datasets ...
[*] GSECA running ...
 === FMM and DD === 
[*] NE threshold: 0.01
[*] Number of Expression Classes: 7
 -- Parallelizing 2 cores ...
[*] FMM Getting thresholds ...
[*] DD Setting expression classes ...
  |======================================================================| 100%
Error in if (mu > x) uniroot(function(t) mnhyper(t) - x, c(0, 1))$root else if (mu <  : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In dhyper(support, m, n, k, log = TRUE) : NaNs produced
2: In d <= d[x - lo + 1] * relErr :
  longer object length is not a multiple of shorter object length
`

I definitely think the issue with my input data but I don't know where to begin looking for the issue. The data isn't my generated data but taken from a study. They are normalized expression counts. 

My code: 

`
M = read.delim("~/Desktop/RSVinput_trunc.tsv")
L = read.delim("~/Desktop/RSV_setlist.tsv")[,1]

# Gene set list
pl = read.gmt.file("~/Desktop/homo_sapiens_human_gmt2.gmt")

res = GSECA_executor(  M # Gene Expression matrix
                     , L # Sample label list
                     , pl # gene set list
                     , outdir = "Results" #outdir folder
                     , analysis = "my_analysis"# analysis name
                     , N.CORES = 2 # number of cores
                     , EMPIRICAL = T # true if empirical p-value is requested
                     , BOOTSTRP = T
                     , nsim = 2 # number of bootstrapping
                     , AS = 0.25 # AS threshold
                     , PEMP = 1 # p.emp threshold
                     , SR   = 0.7 # success rate threshold
                     , toprank = 10 # success rate threshold
                     , iphen = c("CASE", "CNTR") #  phenotype lables
)
`

I'll attach the input files. I had to use a generic gmt file which may be an issue 


[input.zip](https://github.com/matteocereda/GSECA/files/4506645/input.zip)

**Comment by matteocereda** [comment]
There are some issues that we could spot in your data. Regarding the expression data (RSVinput_trunc.tsv):
 1. you are correct, the first column name is "ensembl_gene_id";
 2. you have multiple entries of the gene "ENSG00000000003" (253). you must have one line one gene.

The gene set list file (homo_sapiens_human_gmt2.gmt) that you are providing does not meet the requirments. You must avoid the empty values in each line. You can see details about gmt format [here](https://software.broadinstitute.org/cancer/software/gsea/wiki/index.php/Data_formats#GMT:_Gene_Matrix_Transposed_file_format_.28.2A.gmt.29). If you are interested in GO BP gene set, you might alternatively wanna have a look at the corresponding list in the gene_sets folder (i.e. *gene_sets/msigdb/c5.bp.v6.0.symbols.gmt* , referred [here](https://www.gsea-msigdb.org/gsea/msigdb/genesets.jsp?collection=BP)). 

Hope that this helps

**Comment by sdmiller93** [comment]
That was definitely the issue. Thank you!

**Comment by matteocereda** [comment]
We are welcome. Thanks for posting.
